#!/bin/sh

cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication paraFoam -builtin -touch

cp 0/alpha.water.orig 0/alpha.water
cp 0/U.orig 0/U

foamFormatConvert 0/alpha.water
foamFormatConvert 0/U

runApplication extrudeMesh

for i in 1 2 7 8
do
    runApplication -s $i topoSet -dict topoSetDict$i
    runApplication -s $i refineMesh -dict refineMeshDictX -overwrite
done

for i in 3 4 5 6
do
    runApplication -s $i topoSet -dict topoSetDict$i
    runApplication -s $i refineMesh -dict refineMeshDictY -overwrite
done

runApplication setWaves

runApplication decomposePar

runParallel $(getApplication)

runApplication reconstructPar

runApplication rm -r processor*
